---
dotfiles_repo: "https://github.com/opdavies/dotfiles.git"
dotfiles_repo_local_destination: "~/Code/dotfiles"
dotfiles_files:
  - .composer/composer.json
  - .composer/composer.lock
  - .gitconfig
  - .gitignore-global
  - .ideavimrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  - fish
  - ssh-copy-id
  - wget

homebrew_cask_apps:
  - alfred
  - cyberduck
  - dropbox
  - filezilla
  - firefox
  - google-chome
  - google-drive
  - gpgtools
  - hipchat
  - iterm2
  - sequel-pro
  - spotify
  - skype
  - sublime-text
  - phpstorm
  - virtualbox
  - vlc
