---
- hosts: localhost
  connection: local

  vars_files:
    - vars/dotfiles.yml
    - vars/homebrew.yml
    - vars/mas.yml
    - vars/misc.yml

  tasks:
    - include: tasks/sublime.yml
      tags: [sublime]

  roles:
    - role: karlmdavis.rcm-dotfiles
      tags: [dotfiles]
    - role: geerlingguy.homebrew
      tags: [homebrew]
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: [macos, mas]
    - role: ./roles/macos
      tags: [macos]
