---
- hosts: localhost
  connection: local

  vars_files:
    - vars/dotfiles.yml
    - vars/homebrew.yml
    - vars/mas.yml
    - vars/misc.yml
    - vars/user.yml

  tasks:
    - include: tasks/sudoers.yml
      tags: ['osx']
    - include: tasks/sublime.yml
      tags: ['sublime']
    - include: tasks/macos.yml
      tags: ['macos']

  roles:
    - role: gantsign.antigen
      tags: ['zsh']
    - role: geerlingguy.dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ['mas']
