---
- hosts: all

  vars_files:
    - vars/main.yml

  tasks:
    - { include: tasks/sudoers.yml, tags: ['base', 'sudoers'] }

  roles:
    - { role: geerlingguy.dotfiles, tags: ['dotfiles'] }
    - { role: geerlingguy.homebrew, tags: ['brew'] }
    - { role: sublime, tags: ['sublime'] }

  post_tasks:
    - { include: tasks/fish.yml, tags: ['base'] }
