---
- hosts: all

  vars_files:
    - vars/main.yml

  tasks:
    - { include: tasks/sudoers.yml, tags: ['base', 'sudoers'] }
    - { include: tasks/sublime.yml, tags: ['sublime'] }

  roles:
    - { role: geerlingguy.dotfiles, tags: ['dotfiles'] }
    - { role: geerlingguy.homebrew, tags: ['brew'] }
    - { role: geerlingguy.nodejs, tags: ['node'] }
    - { role: geerlingguy.ruby, tags: ['ruby'] }
    - { role: opdavies.sculpin, tags: ['sculpin'] }
