---
- name: Empty the Dock
  shell: 'dockutil --remove all --no-restart'

- name: Disable launch animation
  osx_defaults:
    domain: com.apple.dock
    key: launchanim
    type: bool
    value: false

- name: Hide open indicators
  osx_defaults:
    domain: com.apple.dock
    key: show-process-indicators
    type: bool
    value: false

- name: Hide recent apps
  osx_defaults:
    domain: com.apple.dock
    key: show-recents
    type: bool
    value: false

- name: Set the icon size of Dock items.
  osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: int
    value: 35
  notify:
    - killall Dock

- name: Automatically hide and show the Dock.
  osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true
  notify:
    - killall Dock

- name: Remove the autohide delay.
  osx_defaults:
    domain: com.apple.dock
    key: autohide-delay
    type: float
    value: 0
  notify:
    - killall Dock
